### ISSUE TITLE
CMD Befehlssatz über FHEM sicherstellen

### ISSUE THREAD

**Issue by BenchR267** [HTWDD-RN/Sensornetzdemo#10]
Momentan ist dieser durch FHEM geschützt und kann nicht angesprochen werden. 
Es muss heraus gefunden werden, wie das geändert werden kann, damit eine reibungsfreie Kommunikation zwischen Frontend-Service und FHEM sicher gestellt werden kann.

Ansatz für Kommunikation (zum Testen) ist http://www.loxwiki.eu/display/LOX/FHEM+Basics

**Comment by MrMong** [comment]
Mit dem FHEM-Modul FHEMWeb ist es möglich eine eigene HTTP-API mit eigenem Port anzubieten. Diese kann mit einer allowed-Modulinstanz gekoppelt werden, in welcher dann festgelegt werden kann, welche Befehle und Geräte außen angefragt / zugegriffen werden können.
[FHEMWeb](https://wiki.fhem.de/wiki/FHEMWEB)

FHEM benutzt weiterhin zur Sicherheit einen Token-Mechanismus. Dieser wird jedesmal bei Neustart von FHEM automatisch neu generiert. Weiterhin kann dieser abgefragt werden indem ein HTTP-GET z.B. `http://localhost:8083/fhem?XHR=1` an FHEM gesendet wird und FHEM diesen dann der GET-Response anhängt. Der Token sieht z.B. so aus: `fhem_397465975744973`
Dieser muss dann an die eigentliche GET-Anfrage mittels Key-Value z.B. `fwcsrf=fhem_397465975744973` angehängt werden.
[CsrfToken-HowTo](https://wiki.fhem.de/wiki/CsrfToken-HowTo)

Z.b. eine HTTP-GET vom Frontend-Service zur Informationsabfrage aller Geräte in FHEM:
`http://localhost:8088/fhem?cmd=jsonlist2&fwcsrf=fhem_397465975744973&XHR=1`
Das `jsonlist2` bewirkt, dass die Daten-Rückgabe von FHEM im JSON-Format erfolgt.
Das Frontend-Service bekommt dann jene Geräte-Informationen, welche in FHEM intern in der allowed-Modulinstanz angegeben sind.
