### ISSUE TITLE
Discover in FS implementieren

### ISSUE THREAD

**Issue by BenchR267** [HTWDD-RN/Sensornetzdemo#15]
Die angezeigten Knoten sollen ihre angebotenen Actions mittels Discover offen legen. Dabei sollen keine Actions im FS-Code definiert sein, sondern diese zur Laufzeit angefragt werden.

**Comment by JVankat** [comment]
Sollte jetzt meinerseits funktionieren, man müsste zurzeit nur noch die RESOURCE_IPS statisch im resourceController ganz oben angeben. Dann wird beim API Start alles automatisch gebaut. Wir sollten das aber jedenfalls noch mit unserem Aufbau testen...

Die Antwort vom /.well-known/core sollte ungefähr so aussehen:

` </.well-known/core>;ct=40,</LED/green>;ct=0;rt=LED;val=1;name=MyLovelyLED;node=PrimarkBillboard`

**Comment by BenchR267** [comment]
Müssen mal schauen, ob wir das noch verwenden können. Vermutlich müssen wir erstmal alles hard coden und das als Ausblick in das nächste Semester mit geben.

**Comment by BenchR267** [comment]
Implementierung steht, finaler Test steht noch aus - sollte aber theoretisch funktionieren und auch in diesem Semester noch vorgeführt werden können.
