### ISSUE TITLE
Websocket zwischen Frontend und FS

### ISSUE THREAD

**Issue by BenchR267** [HTWDD-RN/Sensornetzdemo#16]
Um eine Live-Anpassung des States im Frontend zu ermöglichen, wird statt Polling ein Websocket eingesetzt.
Wenn Änderungen passieren, wird diese automatisch an alle Subscriber (Frontends) mittels Socket gepusht, welche darauf hin ihre UI updaten.

**Comment by JVankat** [comment]
@BenchR267 hab das auf der Frontend-Service Seite vorbereitet. Du kriegst bei jedem Resource-Update das gleiche wie beim GET auf /
