### ISSUE TITLE
RGB-LED mittels Node steuerbar machen

### ISSUE THREAD

**Issue by BenchR267** [HTWDD-RN/Sensornetzdemo#17]
Zuerst ohne CoAP-Anbindung sollte eine RGB-LED mit einem Node verbunden werden. Außerdem sollten entsprechende Funktionen geschrieben werden, damit die angeschlossene LED verschiedene Farben/Helligkeiten darstellen kann.
Konfiguration erfolgt mittels RGB:

Bsp:

```C
void updateColor(int r, int g, int b) {
	// LED sollte entsprechende Farbe annehmen
}
```

Die Werte sind Integer Werte im Bereich [0,255].

**Comment by CarlSchwedes** [comment]
Beim Versuch microcoap Server zu starten schlägt sudo make term fehl:
```
pyterm
AttributeError: 'module' object has no attribute 'Serial'
```

Fehlerbehebung durch deinstallieren von serial und nachinstallieren von pyserial:
`pip uninstall serial && pip install pyserial`

**Comment by MrMong** [comment]
```
void parse_payload_rgb(const char *input, int *rgb, size_t rgb_size)
{
	char *copy = strdup(input);
	char delimiter[] = ";";
	char *splitted_string;

	splitted_string = strtok(copy, delimiter);
	int i = 0;
	while (splitted_string != NULL)
	{
	  rgb[i] = atoi(splitted_string);
	  splitted_string = strtok (NULL, delimiter);
		i++;
		if(i >= rgb_size)
			splitted_string = NULL;
	}		
}
```

**Comment by MrMong** [comment]
Es existiert nun ein neuer COAP-Endpunkt `RGB/dim`. Dieser erwartet einen COAP-POST-Request mit drei durch Semikolon getrennte Integer-Zahlen (RGB) als String-Payload, z.B. `234;0;44`.
Diese werden dann intern als drei Integer-Zahlen geparsed und aktuell in der Konsole ausgegeben.
Als COAP-RESPONSE wird ein 'a' geliefert.
Siehe: a563a5e37245180ce5a8567b2cf2fda6d4a52cf9

Weitere Schritte:
Implementierung der internen Dimm-Funktionalität entsprechend der LED-Hardware.

**Comment by BenchR267** [comment]
Wurde nun ein bisschen angepasst und ist ein one-liner geworden :) 
```C
int parse_payload_rgb(const char *input)
{
    return strtol(input, NULL, 10);
}
```
