### ISSUE TITLE
Dimming-Action muss von Frontend unterstützt werden

### ISSUE THREAD

**Issue by BenchR267** [HTWDD-RN/Sensornetzdemo#19]
Die in #18 implementierte Funktionalität muss von dem Frontend unterstützt werden. Dabei muss außerdem der FS die Action definieren. Dokumentation für die REST-Schnittstelle muss ebenfalls erstellt werden.

Bsp:
```JSON
PUT HTTP/1.1 /:ressource-id:/:action-id:
DIMM:
	{
		"values": [
                    233,
                    12,
                    0
                ]
	}

	response:
	{
		"values": [
                    233,
                    12,
                    0
                ]
	}

```

**Comment by MrMong** [comment]
Hier die Infos zum CoAP-Observe:

[Observe in Node.js](https://github.com/mcollina/node-coap#observeread)
[Observe-Beispiel in Node.js](https://github.com/mcollina/node-coap/blob/master/examples/observe_client.js)
[Aktueller Stand zur Observe-Funktionalität in CoAP](https://tools.ietf.org/html/rfc7641)

Alles rund um das zyklisches Abfragen von Sensorwerten mittels CoAP kann meinem FS-Zwischenbericht aus dem letzten Semester entnommen werden.

**Comment by BenchR267** [comment]
@MrMong das passt eher zu #16, hier geht es ja um die Dimming-Schnittstelle

**Comment by BenchR267** [comment]
Um die Anzahl Requests minimal zu halten, ist eine Diskretisierung zwischen 0 und 255 eventuell sinnvoller als freie Double-Werte zwischen 0 und 1 zu wählen.

**Comment by JVankat** [comment]
Meinst du damit du die Werteänderung nicht kontinuierlich posten musst? Da würde ich sagen, dass du beliebige min und max Werte akzeptieren könntest und entweder im Frontend die stepSize für den Slider definierst (z.B. stepSize=(max-min)/256), oder erst nach dem releasen des Sliders (after-change oder so was) postest. Oder hab ich dich falsch verstanden?

**Comment by BenchR267** [comment]
Genau, geht um die stepsize. 0-255 hat außerdem den Vorteil, dass es `Int` Werte sind, die auch weniger Platz wegnehmen im Payload. Würde also min, max und current jeweils als Integer machen und aus 0, 255 und 130 _(oder whatever)_ festlegen.

**Comment by JVankat** [comment]
Angepasst.

**Comment by BenchR267** [comment]
Momentan ist die RangeAction ein Slider, der Werte zwischen min und max darstellt und auf Änderungen reagiert. Dies muss ausgetauscht werden durch einen Color-Picker, damit wir RGB darstellen können (z.B. mit https://github.com/HubSpot/react-colors-picker).
Außerdem müssen die Änderungen über den ApiClient an das Backend geschickt werden und dabei Steps implementiert werden (also dass nur volle Integer Werte geschickt werden und möglichst nur bei Änderung.

**Comment by MrMong** [comment]
Done.
