### ISSUE TITLE
CoAP-Befehlssatz für CoAP-Clients herausfinden und mittels Copper testen

### ISSUE THREAD

**Issue by BenchR267** [HTWDD-RN/Sensornetzdemo#5]
Momentaner Stand lässt auf diesen Befehl deuten:
```POST coap://[IPv6]:5683/htw/led0```

**Comment by KingMerithim** [comment]
Befehlsatz laut RIOTS CoAP-Implementierung: GET, POST, PUT, DELETE

Bei Copper funktioniert GET, DISCOVER, POST
DELETE bisher ungetestet
PUT brachte, auch nach Anpassung des Quellcodes für die Knoten, keinen Erfolg
