### ISSUE TITLE
FHEM + CoAP-Client dockern

### ISSUE THREAD

**Issue by BenchR267** [HTWDD-RN/Sensornetzdemo#9]
Es gibt scheinbar auch schon fertige Docker-Container für FHEM, auf denen man aufbauen könnte. Ein Beispiel: https://hub.docker.com/r/pipp37/fhem_jessie/

**Comment by MrMong** [comment]
Done.
Habe das Dockerfile aus dem [GitHub-Repo](https://github.com/mkunzmann/docker-fhem) als Vorlage benutzt.

**Comment by BenchR267** [comment]
@MrMong ich glaube, man hätter auch 'eleganter' darauf aufbauen können, ohne den Code zu kopieren. Aber so passt es erstmal denk ich :)
